FROM node:24-alpine3.20

WORKDIR /usr/src/app

COPY package.json yarn.lock turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN yarn install

# Generate Prisma client
RUN yarn run generate-prisma

# Build only the user-app
RUN yarn run build --filter=user-app

CMD ["yarn", "run", "start-user-app"]